os:
  - linux

language: perl

perl:
  - '5.30'
  - 5.28
  - 5.18

script:
  yath test --qvf t/

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers; source ~/travis-perl-helpers/init; build-perl; fi
  - perl -V
  - cpanm --notest Test::More~0.98
