name: Milla

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build tarball with milla
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: 5.32
      - run: cpanm --notest Dist::Milla LWP::Protocol::https Dist::Zilla::Plugin::Test::Perl::Critic Test::Pod JSON::XS Furl::HTTP Test2::V0
      - run: cpanm --notest --installdeps .
      - run: milla build
      - run: ls -l LINE-Bot-API*.tar.gz
      - run: tar tvzf LINE-Bot-API*.tar.gz
      - run: cpanm --verbose LINE-Bot-API*.tar.gz
